<?php
namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;
class ArsipTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$rand_deskripsi = [
            "<p> Arsip  cari gugur Berita ini berisi tentang Kecamatan Kupang Barat. Tempat ini memiliki ombak yang ramah dan tidak terlalu besar.</p>",
            "<p> Arip We proudly present this stunning Boutique Eco Surf Resort located on the Island of Rote and close to the famous T-Land (longest wave in Indonesia), everything you need for your holidays!!</p>",
            "<p>Guests can choose between exclusive suites with sleek décor or 2 bedroom family Bungalow both with spectacular views, Swimming Pool, Volleyball Court, unbelievable sunsets which turn the sky into a kaleidoscopic masterpiece, and as the night falls get ready for the most amazing sky full of stars you have ever seen.</p>",
        ]; 
        //
        DB::table('arsips')->insert([
            [
                'id'             => 1,
                'judul'          => 'Arsip 1',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(1,2)], 
                'ok'             => 1,
                'file'      	 => 'dokument/baru1', 
                'id_admin'       => 1,
                'id_de'          => 5,
                'id_ad'          => 2,
                'publish'        => 'publish',
                'id_publish'     => 2,
                'keterangan'	 => 'keterangan 1',
            ],
            [
                'id'             => 2,
                'id_ad'          => 1,
                'judul'          => 'Arsip 2',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,2)], 
                'id_admin'       => 1,
                'id_publish'     => 3,
                'id_de'          => 2,
                'file'      	 => 'dokument/baru1',
                'keterangan'	 => 'keterangan 2',
                'ok'             => 1,
                'publish'        => 'publish',
            ],
            [
                'id'             => 3,
                'ok'             => 0,
                'id_ad'          => 2,
                'file'      	 => 'dokument/baru1',
                'publish'        => 'belum',
                'judul'          => 'Arsip 3',
                'id_publish'     => 2,
                'id_de'          => 5,
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,2)],                
                'id_admin'       => rand(1,2),
                'keterangan'	 => 'keterangan 3',
            ],
            [
                'id'             => 4,
                'ok'             => 1,
                'publish'        => 'publish',
                'judul'          => 'Arsip 4',
                'file'      	 => 'dokument/baru1',
                'id_jenis'       => 2,
                'id_de'          => 3,
                'id_publish'     => 2,
                'id_ad'          => 2,
                'deskripsi'      => $rand_deskripsi[rand(1,2)], 
                'id_admin'       => rand(1,2),
                'ok'             => 1,
                'keterangan'	 => 'keterangan 4',
            ],
            [
                'id'             => 5,
                'judul'          => 'Arsip 5',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'id_admin'       => rand(1,2),
                'ok'             => 0,
                'id_de'          => 6,
                'id_ad'          => 2,
                'id_publish'     => 2,
                'file'      	 => 'dokument/baru1',
                'publish'        => 'belum',
                'keterangan'	 => 'keterangan 5',
            ],
            [
                'id'             => 6,
                'judul'          => 'Arsip 6',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,2)], 
                'file'      	 => 'dokument/baru1',
                'ok'             => 0, 
                'id_de'          => 7,
                'publish'        => 'belum',
                'id_publish'     => 2,
                'id_admin'       => rand(1,2),
                'id_ad'          => 2,
                'keterangan'	 => 'keterangan 6',
            ],
            [
                'id'             => 7,
                'judul'          => 'Arsip 7',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'id_admin'       => 3,
                'id_de'          => 5,
                'ok'             => 0,
                'publish'        => 'belum',
                'id_publish'     => 2,
                'id_ad'          => 3,
                'file'      	 => 'dokument/baru1',
                'keterangan'     => 'keterangan 5',
            ],
            [
                'id'             => 8,
                'judul'          => 'Arsip 8',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'file'      	 => 'dokument/baru1',
                'id_admin'       => 3,
                'ok'             => 1,
                'id_de'          => 8,
                'id_publish'     => 2,
                'id_ad'          => 2,
                'publish'        => 'publish',
                'keterangan'     => 'keterangan 5',
            ],
            [
                'id'             => 9,
                'judul'          => 'Arsip 9',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'id_admin'       => rand(1,2),
                'ok'             => 1,
                'id_ad'          => 2,
                'id_publish'     => 2,
                'id_de'          => 5,
                'publish'        => 'publish',
                'file'      	 => 'dokument/baru1',
                'keterangan'     => 'keterangan 5',
            ],
            [
                'id'             => 10,
                'judul'          => 'Arsip 10',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'id_admin'       => rand(1,2),
                'ok'             => 1,
                'id_ad'          => 2,
                'id_de'          => 6,
                'file'      	 => 'dokument/baru1',
                'publish'        => 'publish',
                'id_publish'     => 2,
                'keterangan'     => 'keterangan 5',
            ],
            [
                'id'             => 11,
                'judul'          => 'Arsip 11',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'id_admin'       => rand(1,2),
                'ok'             => 1,
                'id_ad'          => 2,
                'id_publish'     => 2,
                'id_de'          => 6,
                'file'      	 => 'dokument/baru1',
                'publish'        => 'publish',
                'keterangan'     => 'keterangan 5',
            ],
            [
                'id'             => 12,
                'judul'          => 'Arsip 12',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'id_admin'       => rand(1,2),
                'id_ad'          => 3,
                'id_de'          => 4,
                'ok'             => 0,
                'id_publish'     => 2,
                'publish'        => 'belum',
                'file'      	 => 'dokument/baru1',
                'keterangan'     => 'keterangan 5',
            ],
            [
                'id'             => 14,
                'judul'          => 'Arsip 14',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'file'      	 => 'dokument/baru1', 
                'id_admin'       => rand(1,2),
                'ok'             => 0,
                'id_de'          => 5,
                'id_publish'     => 2,
                'id_ad'          => 2,
                'publish'        => 'belum',
                'keterangan'     => 'keterangan 5',
            ]
        ]);
    }
}
