<?php
namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;
class BeritaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$rand_deskripsi = [
            "<p>cari gugur Berita ini berisi tentang Kecamatan Kupang Barat. Tempat ini memiliki ombak yang ramah dan tidak terlalu besar. 
            Jadi sangat baik untuk masyarakat  yang tidak bisa bermain selancar atau pun orang yang kurang pandai berenang. 
            Disamping itu, pantai ini juga masih memiliki air yang sangat jernih dan pasir yang bersih.</p>",
            "<p>We proudly present this stunning Boutique Eco Surf Resort located on the Island of Rote and close to the famous T-Land (longest wave in Indonesia), offering unforgettable experiences and making positive contributions to the community. You’ll find yourself immersed in natural beauty, Manduna rock is home to a large number of nesting birds, it is right in front of the Boutique Eco Surf Resort.All rooms have air conditioning and comfortable beds to ensure a great night’s sleep as well as open-air bathrooms with hot water. Enjoy delicious food prepared using locally sourced ingredients by our talented chef ( breakfast, lunch, and dinner). A menu of snacks and drinks is also available to keep you refreshed by the pool or beach during the day. Free Wifi in the restaurant area, unlimited surf transfers to T- Land the main wave, expert surf guides, SUP, snorkeling, bike tours, daily yoga session, airport transfers, everything you need for your holidays!!</p>",

            "<p>Guests can choose between exclusive suites with sleek décor or 2 bedroom family Bungalow both with spectacular views, Swimming Pool, Volleyball Court, unbelievable sunsets which turn the sky into a kaleidoscopic masterpiece, and as the night falls get ready for the most amazing sky full of stars you have ever seen. cari sacry Noelbaki memiliki pantai Air laut yang kadar garam yang lebih tinggi dari air laut pada umumnya. 
            Kadar garam yang tinggi ikan yang hidup di laut ini adalah Paus yaitu Paus Hanas. 
            Pasir dari danau ini terbuat dari kulit kerang dan air yang jernih, 
            namun pada musim angin timur airnya berbusa menambah keindahan pantai di laut ini.</p>",
        ]; 
        //
        DB::table('beritas')->insert([
            [
                'id'             => 1,
                'judul'          => 'Berita 1',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'rating'         => 2,
                'ok'             => 1, 
                'id_admin'       => 1,
                'id_ad'          => 1,
                'id_de'          => 1,
                'id_publish'     => 2,
                'comment_count'  => 2,
                'publish'        => 'publish',
                'keterangan'	 => 'keterangan 1',
            ],
            [
                'id'             => 2,
                'judul'          => 'Berita 2',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,2)], 
                'rating'         => 1, 
                'id_ad'          => 2,
                'id_de'          => 1,
                'id_admin'       => 1,
                'id_publish'     => 3,
                'comment_count'  => 1,
                'keterangan'	 => 'keterangan 2',
                'ok'             => 1,
                'publish'        => 'publish',
            ],
            [
                'id'             => 3,
                'ok'             => 0,
                'publish'        => 'belum',
                'judul'          => 'Berita 3',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,2)], 
                'rating'         => 5, 
                'id_admin'       => rand(1,2),
                'comment_count'  => 0,
                'id_ad'          => 3,
                'id_de'          => 4,
                'id_publish'     => 4,
                'keterangan'	 => 'keterangan 3',
            ],
            [
                'id'             => 4,
                'ok'             => 1,
                'publish'        => 'publish',
                'judul'          => 'Berita 4',
                'id_jenis'       => 2,
                'deskripsi'      => $rand_deskripsi[rand(1,2)], 
                'rating'         => 0,
                'id_de'          => 5, 
                'id_admin'       => rand(1,2),
                'comment_count'  => 0,
                'id_publish'     => 2,
                'ok'             => 1,
                'id_ad'          => 2,
                'keterangan'	 => 'keterangan 4',
            ],
            [
                'id'             => 5,
                'judul'          => 'Berita 5',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'rating'         => 0, 
                'id_admin'       => rand(1,2),
                'comment_count'  => 0,
                'ok'             => 0,
                'id_ad'          => 3,
                'id_de'          => 3,
                'id_publish'     => 2,
                'publish'        => 'belum',
                'keterangan'	 => 'keterangan 5',
            ],
            [
                'id'             => 6,
                'judul'          => 'Berita 6',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,2)], 
                'rating'         => 0,
                'ok'             => 0,
                'id_ad'          => 5,  
                'publish'        => 'belum',
                'id_admin'       => rand(1,2),
                'id_publish'     => 1,
                'comment_count'  => 0,
                'id_de'          => 3,
                'keterangan'	 => 'keterangan 6',
            ],
            [
                'id'             => 7,
                'judul'          => 'Berita 7',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'rating'         => 0, 
                'id_admin'       => rand(1,2),
                'comment_count'  => 0,
                'ok'             => 0,
                'id_ad'          => 1,
                'id_publish'     => 1,
                'id_de'          => 5,
                'publish'        => 'belum',
                'keterangan'     => 'keterangan 5',
            ],
            [
                'id'             => 8,
                'judul'          => 'Berita 8',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'rating'         => 0, 
                'id_admin'       => rand(1,2),
                'comment_count'  => 0,
                'ok'             => 1,
                'id_de'          => 6,
                'id_ad'          => 1,
                'id_publish'     => 1,
                'publish'        => 'publish',
                'keterangan'     => 'keterangan 5',
            ],
            [
                'id'             => 9,
                'judul'          => 'Berita 9',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'rating'         => 0, 
                'id_admin'       => rand(1,2),
                'comment_count'  => 0,
                'ok'             => 1,
                'id_ad'          => 1,
                'id_de'          => 6,
                'id_publish'     => 1,
                'publish'        => 'publish',
                'keterangan'     => 'keterangan 5',
            ],
            [
                'id'             => 10,
                'judul'          => 'Berita 10',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'rating'         => 0, 
                'id_admin'       => rand(1,2),
                'comment_count'  => 0,
                'ok'             => 1,
                'id_de'          => 2,
                'publish'        => 'publish',
                'id_ad'          => 1,
                'id_publish'     => 1,
                'keterangan'     => 'keterangan 5',
            ],
            [
                'id'             => 11,
                'judul'          => 'Berita 11',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'rating'         => 0, 
                'id_admin'       => rand(1,2),
                'comment_count'  => 0,
                'ok'             => 1,
                'id_ad'          => 1,
                'id_de'          => 5,
                'id_publish'     => 1,
                'publish'        => 'publish',
                'keterangan'     => 'keterangan 5',
            ],
            [
                'id'             => 12,
                'judul'          => 'Berita 12',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'rating'         => 0, 
                'id_admin'       => rand(1,2),
                'comment_count'  => 0,
                'id_de'          => 5,
                'ok'             => 0,
                'publish'        => 'belum',
                'id_ad'          => 1,
                'id_publish'     => 1,
                'keterangan'     => 'keterangan 5',
            ],
            [
                'id'             => 14,
                'judul'          => 'Berita 14',
                'id_jenis'       => rand(1,2),
                'deskripsi'      => $rand_deskripsi[rand(0,1)], 
                'rating'         => 0, 
                'id_admin'       => rand(1,2),
                'comment_count'  => 0,
                'id_ad'          => 1,
                'id_de'          => 4,
                'id_publish'     => 1,
                'ok'             => 0,
                'publish'        => 'belum',
                'keterangan'     => 'keterangan 5',
            ]
        ]);
    }
}
